version: "3.7"
services:
  # セクション名については任意の名前で構わない。
  web:
    # Dockerイメージを指定
    image: nginx:latest
    ports:
      # プロキシサーバのポートを指定（ホスト側:コンテナ側）
      - "8080:80"
    volumes:
      # nginxのconfigファイルをマウントしdefault.confへ上書き
      - ./docker-configs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  php:
    # Dockerイメージを指定、PHPバージョンは7.3
    image: php:7-fpm
    # FastCGIサーバのデフォルトポートを使用するためports指定なし
    volumes:
      # 実行対象のPHPファイルをマウント
      - ./src/:/var/phpapp/
